FROM alpine:3.1

# Update
RUN apk add --update python py-pip

# Install app dependencies
RUN pip install Flask

# Bundle app source
COPY auth-server.py /src/auth-server.py

EXPOSE  5000
CMD ["python", "/src/auth-server.py"]
CMD ["python", "/src/dir
-server.py"]
